# Generated by Django 4.2.3 on 2023-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokenea",
            name="height",
            field=models.CharField(max_length=255),
        ),
    ]
