# Generated by Django 4.2.3 on 2023-11-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_pokenea', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokenea',
        ),
    ]
